# Generated by Django 5.2.13 on 2026-04-29 09:30

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('categorie', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('devops', 'DevOps'), ('data', 'Data'), ('autre', 'Autre')], max_length=50)),
                ('niveau_requis', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Quete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('instructions', models.TextField(help_text="Instructions détaillées pour l'utilisateur")),
                ('points', models.IntegerField(default=50)),
                ('type_quete', models.CharField(choices=[('github_repo', 'Créer un repo GitHub'), ('github_commit', 'Faire des commits GitHub'), ('github_file', 'Fichier requis dans repo'), ('quiz', 'Quiz technique'), ('url_submit', 'Soumettre une URL'), ('admin_review', 'Validation formateur')], max_length=50)),
                ('icone', models.CharField(default='⚔️', max_length=10)),
                ('difficulte', models.IntegerField(default=1, help_text='1=Facile 2=Moyen 3=Difficile')),
                ('validation_config', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('bio', models.TextField(blank=True)),
                ('github_username', models.CharField(blank=True, max_length=100)),
                ('points', models.IntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserCompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.competence')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'competence')},
            },
        ),
        migrations.CreateModel(
            name='UserQuete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('non_commence', 'Non commencé'), ('en_cours', 'En cours'), ('soumis', 'Soumis - en attente'), ('valide', 'Validé ✅'), ('refuse', 'Refusé ❌')], default='non_commence', max_length=20)),
                ('soumission', models.TextField(blank=True, help_text='URL, réponse quiz, username GitHub...')),
                ('soumission_data', models.JSONField(blank=True, default=dict)),
                ('feedback', models.TextField(blank=True, help_text='Message de validation ou refus')),
                ('date_soumission', models.DateTimeField(blank=True, null=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('points_gagnes', models.IntegerField(default=0)),
                ('quete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.quete')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quetes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'quete')},
            },
        ),
    ]
